import React, { useState } from 'react';
import { DecisionRecord } from '../types/decision';
import { X, Copy, Download, Check, FileText } from 'lucide-react';

interface ExportModalProps {
  isOpen: boolean;
  onClose: () => void;
  record: DecisionRecord | null;
}

export const ExportModal: React.FC<ExportModalProps> = ({
  isOpen,
  onClose,
  record
}) => {
  if (!isOpen || !record) return null;

  const [copied, setCopied] = useState(false);

  const generateMarkdown = () => {
    const { input, result } = record;
    const comp = result.thinkingCompleteness;

    return `# BLINDSPOT EXECUTIVE DECISION BRIEF
**Title:** ${input.title}
**Category:** ${input.category}
**Timeframe:** ${input.timeframe}
**Date:** ${new Date(result.analyzedAt).toLocaleDateString()}

---

## 📊 ANALYTICAL METRICS
- **Thinking Completeness Index:** ${comp ? comp.score : 82}%
- **Analytical Risk Indicator:** ${result.riskIndicator}%
- **Philosophy:** BlindSpot does not make the decision for you. It makes your thinking better.

---

## 📝 EXECUTIVE SUMMARY
${result.executiveSummary}

---

## 📌 FACTS vs ASSUMPTIONS vs UNKNOWNS
### Facts (Explicitly Provided)
${result.facts ? result.facts.map(f => `- [${f.category}] ${f.text}`).join('\n') : '- N/A'}

### Unexamined Assumptions
${result.assumptions ? result.assumptions.map(a => `- [${a.riskLevel.toUpperCase()} RISK] ${a.text}`).join('\n') : '- N/A'}

### Critical Unknowns
${result.unknowns ? result.unknowns.map(u => `- **Question:** ${u.question}\n  - **Why Critical:** ${u.whyCritical}\n  - **Verification:** ${u.verificationStep}`).join('\n') : '- N/A'}

---

## ⚠️ BLIND SPOTS & COGNITIVE SIGNALS
${result.blindSpots.map((bs, i) => `
### ${i + 1}. [${bs.severity.toUpperCase()} SEVERITY] ${bs.title} (${bs.category})
- **Summary:** ${bs.summary}
- **Why It Matters:** ${bs.whyItMatters}
- **Unverified Variable:** ${bs.whatIsUnknown}
- **Reflection Prompt:** ${bs.reflectionQuestion}
${bs.challengeNotes ? `- **Your Counter-Evidence Notes:** ${bs.challengeNotes}` : ''}
`).join('\n')}

---

## 🔄 FLIP THE DECISION ANALYSIS
**Opposite Path Evaluated:** ${result.flipDecision ? result.flipDecision.title : 'N/A'}
- **Overlooked Benefits:** ${result.flipDecision ? result.flipDecision.overlookedBenefits.join('; ') : 'N/A'}
- **Overlooked Costs:** ${result.flipDecision ? result.flipDecision.overlookedCosts.join('; ') : 'N/A'}

---

## 🗺️ BEFORE vs AFTER THINKING MAP
- **Before Thinking:** "${result.beforeAfterMap ? result.beforeAfterMap.initialThinking : ''}"
- **What BlindSpot Revealed:** ${result.beforeAfterMap ? result.beforeAfterMap.whatBlindSpotRevealed.join('; ') : ''}
- **Updated Understanding:** "${result.beforeAfterMap ? result.beforeAfterMap.updatedUnderstanding : ''}"

---

## 💡 STRATEGIC ACTION PLAN
${result.recommendations.map((rec, i) => `${i + 1}. ${rec}`).join('\n')}

---
*Generated by BlindSpot AI Decision Intelligence System*
`;
  };

  const handleCopy = () => {
    const md = generateMarkdown();
    navigator.clipboard.writeText(md);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
    const md = generateMarkdown();
    const blob = new Blob([md], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `BlindSpot_Brief_${record.input.category}_${Date.now()}.md`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-950/80 backdrop-blur-sm animate-in fade-in duration-150">
      <div className="w-full max-w-2xl bg-slate-900 border border-slate-800 rounded-2xl shadow-2xl p-6 space-y-5 relative">
        <button
          onClick={onClose}
          className="absolute top-4 right-4 p-1.5 rounded-lg text-slate-400 hover:text-white hover:bg-slate-800"
        >
          <X className="w-4 h-4" />
        </button>

        <div className="flex items-center space-x-2">
          <FileText className="w-5 h-5 text-indigo-400" />
          <h3 className="text-lg font-bold text-white">Export Decision Brief</h3>
        </div>

        {/* Markdown preview box */}
        <div className="bg-slate-950 border border-slate-800 rounded-xl p-4 max-h-80 overflow-y-auto font-mono text-xs text-slate-300 whitespace-pre-wrap">
          {generateMarkdown()}
        </div>

        <div className="flex items-center justify-between pt-2">
          <span className="text-xs text-slate-500">Formatted Markdown Report</span>

          <div className="flex items-center space-x-3">
            <button
              onClick={handleCopy}
              className="text-xs font-semibold px-4 py-2 rounded-xl bg-slate-800 hover:bg-slate-700 text-slate-200 border border-slate-700 flex items-center space-x-1.5"
            >
              {copied ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5 text-slate-400" />}
              <span>{copied ? 'Copied to Clipboard!' : 'Copy Markdown'}</span>
            </button>

            <button
              onClick={handleDownload}
              className="text-xs font-bold px-5 py-2 rounded-xl bg-indigo-600 hover:bg-indigo-500 text-white flex items-center space-x-1.5 shadow-md"
            >
              <Download className="w-3.5 h-3.5" />
              <span>Download .md File</span>
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};
